puts "Destroying Data..."
puts 
Character.destroy_all 

puts "Begining Seeding Database..."
puts 

puts "Creating All Hero Seeds..."
puts 
###DPS####
puts "Creating DPS..."
puts 
Character.create(
    name: "Reaper", 
    role: "Damage", 
    hero_card: '/images/icons/Icon-Reaper.png', 
    role_card: '/images/icons/Icon-Damage.png',
    name_two: "Gabriel Reyes",
    age: 58,
    occupation: 'Mercenary',
    base_of_operation: 'Los Angeles, California',
    affiliation: "United States Military (formerly), Overwatch (formerly), Blackwatch (formerly), Talon (Council Member)",
    hero_story: 'Some speak of a black-robed terrorist known only as the Reaper. His identity and motives are a mystery. What is known is that where he appears, death follows.
    The Reaper is an extremely volatile mercenary, a ruthless and remorseless killer responsible for terrorist attacks across the world. He has fought in many armed conflicts in the last decades, showing no loyalty to any cause or organization.
    Survivors have described a black shadow ghosting unscathed through the most hellish battlefields. The few bodies recovered of those he kills are pale, empty husks drained of life, their cells showing signs of intense degradation. It is possible that he is a byproduct of failed genetic alteration which forces his cells to simultaneously decay and regenerate at a hyper-accelerated rate.
    Those attempting to track his movements have begun to see a pattern in his appearances. They believe that Reaper is hunting former Overwatch agents and systematically eliminating them.',
    hero_image_one: '/images/heroImages/reaper/Reaper-page-one.png',
    hero_image_two: '/images/heroImages/reaper/Reaper-page-two.png',
    hero_gameplay_video: 'placeholder',
    hero_gameplay_description: 'Hellfire Shotguns, the ghostly ability to become immune to damage, and the power to step between shadows make Reaper one of the deadliest beings on Earth.',
    hp: 250,
    armor: 0,
    shields: 0,
    total_hp: 250,
    hero_difficulty: 1,
    playstyle: 'Flanker/Tank Buster',
    weapon_one_image: "/images/heroImages/reaper/Reaper-shotgun.png",
    weapon_one_name: "Hellfire Shotguns",
    weapon_one_description: "Short-range spread weapons",
    weapon_one_type: "Short-range spread hitscan",
    weapon_two_image: "N/A",
    weapon_two_name: "N/A",
    weapon_two_description: "N/A",
    weapon_two_type: "N/A",
    passive_image: "/images/heroImages/reaper/Reaper-passive.png",
    passive_name: "The Reaping",
    passive_description: "Dealing damage heals you.",
    ability_one_image: "/images/heroImages/reaper/Reaper-shadow-step.png",
    ability_one_name: "Shadow Step",
    ability_one_description: "Teleport to a targeted location.",
    ability_two_image: "/images/heroImages/reaper/Reaper-wraith-form.png",
    ability_two_name: "Wraith Form",
    ability_two_description: "Move faster and become invulnerable, but you cannot shoot.",
    ability_three_image: "N/A",
    ability_three_name: "N/A",
    ability_three_description: "N/A",
    ultimate_image: "/images/heroImages/reaper/Reaper-death-blossom.png",
    ultimate_name: "Death Blossom",
    ultimate_description: "Damage all nearby enemies.",
    healing_type: "N/A",
    barrier: false,
    barrier_health: 0  )
Character.create(
    name: "Widowmaker", 
    role: "Damage", 
    hero_card: '/images/icons/Icon-Widowmaker.png', 
    role_card: '/images/icons/Icon-Damage.png', 
    name_two: "Amélie Lacroix (née Guillard)",
    age: 33,
    occupation: "Ballet dancer (formerly), Assassin",
    base_of_operation: "Annecy, France",
    affiliation: "Talon",
    hero_story: "Widowmaker is the perfect assassin: a patient, ruthlessly efficient killer who shows neither emotion nor remorse.
    It is believed that in her former life, Widowmaker was married to Gérard Lacroix, an Overwatch agent spearheading operations against the Talon terrorist organization. After several unsuccessful attempts to eliminate Gérard, Talon decided to change its focus to his wife, Amélie. Talon operatives kidnapped her and subjected her to an intense program of neural reconditioning. They broke her will, suppressed her personality, and reprogrammed her as a sleeper agent. She was eventually found by Overwatch agents, apparently none the worse for wear, and returned to her normal life.
    Two weeks later she killed Gérard in his sleep.
    Her mission complete, Amélie returned to Talon, and they completed the process of turning her into a living weapon. She was given extensive training in the covert arts, and then her physiology was altered, drastically slowing her heart, which turned her skin cold and blue and numbed her ability to experience human emotion. Amélie was gone.
    Now, Widowmaker is Talon's most effective assassin, feeling little save the satisfaction of a job well done.",
    hero_image_one: "/images/heroImages/widowmaker/Widow-page-one.png",
    hero_image_two: "/images/heroImages/widowmaker/Widow-page-two.png",
    hero_gameplay_video: "Placeholder",
    hero_gameplay_description: "Widowmaker equips herself with whatever it takes to eliminate her targets, including mines that dispense poisonous gas, a visor that grants her squad infra-sight, and a powerful sniper rifle that can fire in fully-automatic mode.",
    hp: 175,
    armor: 0,
    shields: 0,
    total_hp: 175,
    playstyle: "Sniper/Long-range Hitscan",
    hero_difficulty: 2,
    weapon_one_image: "/images/heroImages/widowmaker/Widow-sniper.png",
    weapon_one_name: "Widow's Kiss",
    weapon_one_description: "Automatic assault weapon.",
    weapon_one_type: "Hitscan",
    weapon_two_image: "/images/heroImages/widowmaker/Widow-sniper.png",
    weapon_two_name: "Sniper Mode",
    weapon_two_description: "Hold for long-ranged sniper weapon.",
    weapon_two_type: "Hitscan",
    passive_image: "N/A",
    passive_name: "N/A",
    passive_description: "N/A",
    ability_one_image: "/images/heroImages/widowmaker/Widow-grapple.png",
    ability_one_name: "Grappling Hook",
    ability_one_description: "Launch a hook that pulls you towards a ledge.",
    ability_two_image: "/images/heroImages/widowmaker/Widow-venom.png",
    ability_two_name: "Venom Mine",
    ability_two_description: "Launch a poison trap.",
    ability_three_image: "N/A",
    ability_three_name: "N/A",
    ability_three_description: "N/A",
    ultimate_image: "/images/heroImages/widowmaker/Widow-infra-sight.png",
    ultimate_name: "Infra-sight",
    ultimate_description: "Provide your team with a view of the enemy's location.",
    healing_type: "N/A",
    barrier: false,
    barrier_health: 0)
Character.create(
    name: "Tracer",
    role: "Damage", 
    hero_card: '/images/icons/Icon-Tracer.png', 
    role_card: '/images/icons/Icon-Damage.png',
    name_two: "	Lena Oxton",
    age: 26,
    occupation: "Adventurer , Pilot, Overwatch agent",
    base_of_operation: "London, United Kingdom (formerly), Watchpoint: Gibraltar",
    affiliation: "Royal Air Force (formerly), Overwatch ",
    hero_story: "The former Overwatch agent known as Tracer is a time-jumping adventurer and an irrepressible force for good.
    Lena Oxton  was the youngest person ever inducted into Overwatch's experimental flight program. Known for her fearless piloting skills, she was handpicked to test the prototype of a teleporting fighter, the Slipstream. But during its first flight, the aircraft's teleportation matrix malfunctioned, and it disappeared. Lena was presumed dead.
    She reappeared months later, but her ordeal had greatly changed her: her molecules had been desynchronized from the flow of time. Suffering from 'chronal disassociation,' she was a living ghost, disappearing for hours and days at a time. Even for the brief moments she was present, she was unable to maintain physical form.
    Overwatch's doctors and scientists were stumped, and Tracer's case seemed hopeless until a scientist named Winston designed the chronal accelerator, a device capable of keeping Tracer anchored in the present. In addition, it gave Tracer the ability to control her own time, allowing her to speed it up and slow it down at will. With her newfound skills, she became one of Overwatch's most effective agents.
    Since Overwatch's dissolution, Tracer has continued to right wrongs and fight the good fight wherever the opportunity presents itself.",
    hero_image_one: "/images/heroImages/tracer/Tracer-page-one.png",
    hero_image_two: "/images/heroImages/tracer/Tracer-page-two.png",
    hero_gameplay_video: "Placeholder",
    hero_gameplay_description: "Toting twin pulse pistols, energy-based time bombs, and rapid-fire banter, Tracer is able to 'blink' through space and rewind her personal timeline as she battles to right wrongs the world over.",
    hp: 150,
    armor: 0,
    shields: 0,
    total_hp: 150,
    playstyle: "Flanker/Dive",
    hero_difficulty: 2,
    weapon_one_image: "/images/heroImages/tracer/Tracer-pistol.png",
    weapon_one_name: "Pulse Pistols",
    weapon_one_description: "Short-range automatic weapons.",
    weapon_one_type: "Hitscan",
    weapon_two_image: "N/A",
    weapon_two_name: "N/A",
    weapon_two_description: "N/A",
    weapon_two_type: "N/A",
    passive_image: "N/A",
    passive_name: "N/A",
    passive_description: "N/A",
    ability_one_image: "/images/heroImages/tracer/Tracer-blink.png",
    ability_one_name: "Blink",
    ability_one_description: "Teleport in the direction you are moving.",
    ability_two_image: "/images/heroImages/tracer/Tracer-recall.png",
    ability_two_name: "Recall",
    ability_two_description: "Travel back in time to your previous location and health. (3 seconds)",
    ability_three_image: "N/A",
    ability_three_name: "N/A",
    ability_three_description: "N/A",
    ultimate_image: "/images/heroImages/tracer/Tracer-pulse.png",
    ultimate_name: "Pulse Bomb",
    ultimate_description: "Throw out a powerful sticky explosive.",
    healing_type: "N/A",
    barrier: false,
    barrier_health: 0)
Character.create(
    name: "Torbjorn", 
    role: "Damage", 
    hero_card: '/images/icons/Icon-Torbjorn.png', 
    role_card: '/images/icons/Icon-Damage.png',
    name_two: "Torbjörn Lindholm",
    age: 57,
    occupation: "Weapon designer, Chief Engineer (formerly)",
    base_of_operation: "Gothenburg, Sweden",
    affiliation: "SST Laboratories (formerly), Ironclad Guild (formerly),  Overwatch (formerly)",
    hero_story: "At its height, Overwatch possessed one of the most advanced armaments on the planet, which could be traced to the workshop of an ingenious engineer named Torbjörn Lindholm.
    Before the Omnic Crisis, Torbjörn had gained notoriety for designing weapons systems used by countries around the world. However, his belief that technology must serve a better vision for humanity put him at odds with his employers, who desired to control his weapons using networked computer intelligence.
    Torbjörn had a deep mistrust of sentient robotic intelligence, and while many of his peers wrote this off as paranoia, his worst fears were realized when the robot populations of the world turned against their human creators during the Omnic Crisis. Because of his engineering genius, he was recruited to join the original Overwatch strike team, and his many inventions proved integral to ending the crisis. In the years that followed, Overwatch became an international peacekeeping force, and Torbjörn remained a critical resource for all of its technological needs and signature weapons systems.
    But in the aftermath of Overwatch's fall, many of Torbjörn's weapons were stolen or stashed away around the world. Feeling responsible for his creations, Torbjörn is determined to stop them from falling into the wrong hands and wreaking havoc on the innocent.",
    hero_image_one: "/images/heroImages/torbjorn/Torbjorn-page-one.png",
    hero_image_two: "/images/heroImages/torbjorn/Torbjorn-page-two.png",
    hero_gameplay_video: "Placeholder",
    hero_gameplay_description: "Torbjörn's extensive arsenal includes a rivet gun, hammer, and a personal forge that he can use to build turrets.",
    hp: 200,
    armor: 50,
    shields: 0,
    total_hp: 250,
    playstyle: "Builder",
    hero_difficulty: 2,
    weapon_one_image: "/images/heroImages/torbjorn/Torbjorn-gun.png",
    weapon_one_name: "Rivet Gun & Rivet Gun - Alt Fire",
    weapon_one_description: "Primary - Slow firing, long-ranged weapon.  Secondary - Inaccurate but powerful short-range weapon",
    weapon_one_type: "Projectile",
    weapon_two_image: "/images/heroImages/torbjorn/Torbjorn-hammer.png",
    weapon_two_name: "Forge Hammer",
    weapon_two_description: "Swing to repair your turret or damage an enemy.",
    weapon_two_type: "Melee Weapon.",
    passive_image: "N/A",
    passive_name: "N/A",
    passive_description: "N/A",
    ability_one_image: "/images/heroImages/torbjorn/Torbjorn-turret.png",
    ability_one_name: "Deploy Turret",
    ability_one_description: "Deploy a self building turret.",
    ability_two_image: "/images/heroImages/torbjorn/Torbjorn-overload.png",
    ability_two_name: "Overload",
    ability_two_description: "Gain additional armor as well as improved attack, movement, and reload speed.",
    ability_three_image: "N/A",
    ability_three_name: "N/A",
    ability_three_description: "N/A",
    ultimate_image: "/images/heroImages/torbjorn/Torbjorn-molten.png",
    ultimate_name: "Molten Core",
    ultimate_description: "Create pools of molten slag that damage enemies. Deals additional damage to armor.",
    healing_type: "N/A",
    barrier: false,
    barrier_health: 0)
Character.create(
    name: "Symmetra", 
    role: "Damage", 
    hero_card: '/images/icons/Icon-Symmetra.png', 
    role_card: '/images/icons/Icon-Damage.png',
    name_two: "Satya Vaswani (सत्य वासवानी)",
    age: 28,
    occupation: "Architech",
    base_of_operation: "Utopaea, India",
    affiliation: "Vishkar Corporation",
    hero_story: "Symmetra literally bends reality. By manipulating hard-light constructs, she crafts the world as she wishes it to be, in hopes of engineering a perfect society.
    Following the Omnic Crisis, the Vishkar Corporation of southern India began the laborious process of creating new, self-sustaining cities to house the nation's displaced population. One such city, Utopaea, was created using radical hard-light technology that enabled its architechs to shape the city's streets, utilities, and living spaces in the blink of an eye.
    After she was identified as one of the few capable of becoming a light-bending architech, young Satya Vaswani was plucked from extreme poverty and placed in the care of Vishkar's architech academy, never to return home. Isolated and lonely in her new life, Satya immersed herself in her education and training. She quickly grasped the applications of the technology and was one of the top students in her class. Satya approached hard-light manipulation differently than her peers, with their more procedural, mechanical constructions, instead weaving her constructs in the motions of the traditional dance of her homeland.
    Though she was one of Utopaea's top architechs, the Vishkar Corporation saw far greater potential in Satya's abilities. Giving her the moniker 'Symmetra,' Vishkar sent her on clandestine missions around the world to uphold its corporate interests and expand its influence into other countries.
    Symmetra believes her actions serve the greater good in society. But there are times when she wonders whether the control and order she desires are truly best for humanity.",
    hero_image_one: "/images/heroImages/symmetra/Symmetra-page-one.png",
    hero_image_two: "/images/heroImages/symmetra/Symmetra-page-two.png",
    hero_gameplay_video: "Placeholder",
    hero_gameplay_description: "Symmetra utilizes her Photon Projector to dispatch adversaries, shield her associates, construct teleportation pads and deploy particle-blasting Sentry Turrets.",
    hp: 100,
    armor: 0,
    shields: 125,
    total_hp: 225,
    playstyle: "Builder/Architect",
    hero_difficulty: 2,
    weapon_one_image: "/images/heroImages/symmetra/Symmetra-gun.png",
    weapon_one_name: "Photon Projector",
    weapon_one_description: "Short-range beam weapon with increasing damage. Damaging Barriers does not consume ammunition.",
    weapon_one_type: "Beam",
    weapon_two_image: "/images/heroImages/symmetra/Symmetra-gun.png",
    weapon_two_name: "Photon Projector",
    weapon_two_description: "Hold to charge, release to fire explosive orb",
    weapon_two_type: "Projectile",
    passive_image: "N/A",
    passive_name: "N/A",
    passive_description: "N/A",
    ability_one_image: "/images/heroImages/symmetra/Symmetra-turret.png",
    ability_one_name: "Sentry Turret",
    ability_one_description: "Deploy a small turret that damages and slows enemies.",
    ability_two_image: "/images/heroImages/symmetra/Symmetra-teleporter.png",
    ability_two_name: "Teleporter",
    ability_two_description: "Create two teleporters that enable instant travel between them.",
    ability_three_image: "N/A",
    ability_three_name: "N/A",
    ability_three_description: "N/A",
    ultimate_image: "/images/heroImages/symmetra/Symmetra-barrier.png",
    ultimate_name: "Photon Barrier",
    ultimate_description: "Deploy a massive energy barrier. (5,000 HP)",
    healing_type: "N/A",
    barrier: false,
    barrier_health: 0 )
Character.create(
    name: "Sombra", 
    role: "Damage", 
    hero_card: '/images/icons/Icon-Sombra.png', 
    role_card: '/images/icons/Icon-Damage.png',
    name_two: "Olivia Colomar",
    age: 30,
    occupation: "Hacker",
    base_of_operation: "Dorado, Mexico",
    affiliation: "Los Muertos (formerly), Talon (currently)",
    hero_story: "One of the world's most notorious hackers, Sombra uses information to manipulate those in power.
    Long before she took up the alias 'Sombra,' ░░░░░░ was among the thousands of children who were left orphaned in the aftermath of the Omnic Crisis. With much of her country's infrastructure destroyed, she survived by utilizing her natural gifts with hacking and computers.
    After ░░░░░░ was taken in by Mexico's Los Muertos gang, she aided it in its self-styled revolution against the government. Los Muertos believed that the rebuilding of Mexico had primarily benefited the rich and the influential, leaving behind those who were most in need of assistance.
    Following her many conquests, ░░░░░░ was supremely confident in her skills, but she was caught unprepared when she stumbled into the web of a global conspiracy—one that had also noticed her. With her security irreparably compromised, ░░░░░░ was forced to delete all traces of her identity and went into hiding.
    She later reemerged as Sombra, upgraded and determined to find out the truth behind the conspiracy she had uncovered. Sombra launched an even more audacious string of hacks, and her exploits earned her no shortage of admirers, including Talon. She joined the organization's ranks and is believed to have contributed to its massive cyberattacks against corporations with strong ties to their governments. These efforts incited a popular revolution in Mexico against LumériCo and breached the security of Volskaya Industries, the manufacturing arm of Russia's anti-omnic defense.
    Now, with Talon's extensive resources to call upon, Sombra can focus on her true goal: to unravel the conspiracy and use the power behind it to her own ends.",
    hero_image_one: "/images/heroImages/sombra/Sombra-page-one.png",
    hero_image_two: "/images/heroImages/sombra/Sombra-page-two.png",
    hero_gameplay_video: "Placeholder",
    hero_gameplay_description: "Stealth and debilitating attacks make Sombra a powerful infiltrator. Her hacking can disrupt her enemies, ensuring they're easier to take out, while her EMP provides the upper hand against multiple foes at once. Sombra’s ability to Translocate and camouflage herself makes her a hard target to pin down.",
    hp: 200,
    armor: 0,
    shields: 0,
    total_hp: 200,
    playstyle: "Flanker/Dive/Crowd Control",
    hero_difficulty: 3,
    weapon_one_image: "/images/heroImages/sombra/Sombra-gun.png",
    weapon_one_name: "Machine Pistol",
    weapon_one_description: "Short-range automatic weapon",
    weapon_one_type: "Short-range large spread hitscan",
    weapon_two_image: "N/A",
    weapon_two_name: "N/A",
    weapon_two_description: "N/A",
    weapon_two_type: "N/A",
    passive_image: "/images/heroImages/sombra/Sombra-passive.png",
    passive_name: "Opportunist",
    passive_description: "You detect critically injured enemies through walls.",
    ability_one_image: "/images/heroImages/sombra/Sombra-translocator.png",
    ability_one_name: "Translocator",
    ability_one_description: "Throw a beacon, then press E again to teleport to it. Press ABILITY 2 to remove it.",
    ability_two_image: "/images/heroImages/sombra/Sombra-stealth.png",
    ability_two_name: "Stealth",
    ability_two_description: "Become invisible and move quickly.",
    ability_three_image: "/images/heroImages/sombra/Sombra-hack.png",
    ability_three_name: "Hack",
    ability_three_description: "Hold to hack. Hacked enemies cannot use abilities. Hacked health packs spawn faster but can't be used by enemies. Taking damage interrupts the hack attempt.",
    ultimate_image: "/images/heroImages/sombra/Sombra-ultimate.png",
    ultimate_name: "EMP",
    ultimate_description: "Hack enemies and destroy enemy shields and barriers around you.",
    healing_type: "N/A",
    barrier: false,
    barrier_health: 0)
Character.create(
    name: "Soldier 76", 
    role: "Damage", 
    hero_card: '/images/icons/Icon-Soldier_76.png', 
    role_card: '/images/icons/Icon-Damage.png',
    name_two: "John Francis 'Jack' Morrison",
    age: 55,
    occupation: "Vigilante",
    base_of_operation: "Unknown",
    affiliation: "United States Military (formerly), Overwatch (formerly)",
    hero_story: "Currently the target of an international manhunt, the vigilante known as Soldier: 76 wages a personal war to expose the truth behind Overwatch's collapse.
    Soldier: 76 revealed himself in a string of attacks that crisscrossed the globe, targeting financial institutions, shadowy corporations, and secure Overwatch facilities. Though to the outside world his motives are inscrutable, there are those who claim that he is a former Overwatch agent, determined to shed light on the conspiracy that brought down the organization.
    While his true identity remains a mystery, he is believed to have been trained as a member of the American 'soldier enhancement program.' He possesses physical capabilities exceeding those of a conventional soldier's, as well as other augmentations that make him a peerless combatant. In addition, he utilizes a cutting-edge arsenal, much of it stolen in raids on Overwatch installations.
    Unrelenting in his search to find those responsible for Overwatch's fall, Soldier: 76 will stop at nothing to bring them to justice.",
    hero_image_one: "/images/heroImages/soldier/Soldier-page-one.png",
    hero_image_two: "/images/heroImages/soldier/Soldier-page-two.png",
    hero_gameplay_video: "Placeholder",
    hero_gameplay_description: "Armed with cutting-edge weaponry, including an experimental pulse rifle that’s capable of firing spirals of high-powered Helix Rockets, Soldier: 76 has the speed and support know-how of a highly trained warrior.",
    hp: 200,
    armor: 0,
    shields: 0,
    total_hp: 200,
    playstyle: "Full Auto Hitscan",
    hero_difficulty: 1,
    weapon_one_image: "/images/heroImages/soldier/Soldier-gun.png",
    weapon_one_name: "Heavy Pulse Rifle",
    weapon_one_description: "Automatic assault weapon.",
    weapon_one_type: "Hitscan",
    weapon_two_image: "N/A",
    weapon_two_name: "N/A",
    weapon_two_description: "N/A",
    weapon_two_type: "N/A",
    passive_image: "N/A",
    passive_name: "N/A",
    passive_description: "N/A",
    ability_one_image: "/images/heroImages/soldier/Soldier-sprint.png",
    ability_one_name: "Sprint",
    ability_one_description: "Run faster while moving forward.",
    ability_two_image: "/images/heroImages/soldier/Soldier-heal.png",
    ability_two_name: "Biotic Field",
    ability_two_description: "Deploy a field that heals you and your allies.",
    ability_three_image: "/images/heroImages/soldier/Soldier-rockets.png",
    ability_three_name: "Helix Rockets",
    ability_three_description: "Launch a volley of explosive rockets.",
    ultimate_image: "/images/heroImages/soldier/Soldier-visor.png",
    ultimate_name: "Tactical Visor",
    ultimate_description: "Automatically aims your weapon at targets in view.", 
    healing_type: "N/A", 
    barrier: false, 
    barrier_health: 0 )
Character.create(
    name: "Pharah", 
    role: "Damage",
    hero_card: '/images/icons/Icon-Pharah.png', 
    role_card: '/images/icons/Icon-Damage.png',
    name_two: "Fareeha Amari (فاريها عماري)",
    age: 32,
    occupation: "Security Chief",
    base_of_operation: "Giza, Egypt",
    affiliation: "Egyptian Army (formerly), Helix Security International",
    hero_story: "Fareeha Amari's commitment to duty runs in her blood. She comes from a long line of highly decorated soldiers and burns with the desire to serve with honor.
    As a child, Fareeha dreamed of following in her mother's footsteps and joining the global peacekeeping force, Overwatch. She enlisted in the Egyptian army, and her dogged persistence and tactical prowess caused her to rise up through the officer ranks. She was a courageous leader and earned the loyalty of all who served under her. With her exemplary record, Fareeha was well placed to join the ranks of Overwatch, but before she had that opportunity, Overwatch was disbanded.
    After leaving the army with a commendation for distinguished service, she was offered employment with Helix Security International, a private security firm contracted to defend the artificial intelligence research facility beneath the Giza Plateau. The top-secret facility was touted as vital to the safety of not only the region but countries across the globe. Fareeha gladly accepted the choice assignment and received training in the Raptora Mark VI, an experimental combat suit designed for rapid mobility and devastating firepower.
    Under the call sign 'Pharah,' she works to safeguard the AI installation. Though she mourns Overwatch's passing, she still dreams of fighting the good fight and making a difference on a global scale.",
    hero_image_one: "/images/heroImages/pharah/Pharah-page-one.png",
    hero_image_two: "/images/heroImages/pharah/Pharah-page-two.png",
    hero_gameplay_video: "Placeholder",
    hero_gameplay_description: "Soaring through the air in her combat armor, and armed with a launcher that lays down high-explosive rockets, Pharah is a force to be reckoned with.",
    hp: 200,
    armor: 0,
    shields: 0,
    total_hp: 200,
    playstyle: "Flying/Projectile/Crowd Control",
    hero_difficulty: 1,
    weapon_one_image: "/images/heroImages/pharah/Pharah-gun.png",
    weapon_one_name: "Rocket Launcher",
    weapon_one_description: "Long-range explosive projectile",
    weapon_one_type: "Projectile",
    weapon_two_image: "N/A",
    weapon_two_name: "N/A",
    weapon_two_description: "N/A",
    weapon_two_type: "N/A",
    passive_image: "/images/heroImages/pharah/Pharah-hover.png",
    passive_name: "Hover Jets",
    passive_description: "Hold to hover",
    ability_one_image: "/images/heroImages/pharah/Pharah-jet.png",
    ability_one_name: "Jump Jet",
    ability_one_description: "Fly rapidly upwards",
    ability_two_image: "/images/heroImages/pharah/Pharah-boop.png",
    ability_two_name: "Concussive Blast",
    ability_two_description: "Launch an explosive blast to knock back enemies",
    ability_three_image: "N/A",
    ability_three_name: "N/A",
    ability_three_description: "N/A",
    ultimate_image: "/images/heroImages/pharah/Pharah-barrage.png",
    ultimate_name: "Barrage",
    ultimate_description: "Launch a continuous volley of mini-rockets.",
    healing_type: "N/A",
    barrier: false,
    barrier_health: 0 )
Character.create(
    name: "Mei", 
    role: "Damage", 
    hero_card: '/images/icons/Icon-Mei.png', 
    role_card: '/images/icons/Icon-Damage.png',
    name_two: "Mei-Ling Zhou (周美灵)",
    age: 31,
    occupation: "Climatologist",
    base_of_operation: "Xi'an, China",
    affiliation: "Overwatch, Atlas News",
    hero_story: "Mei is a scientist who has taken the fight to preserve the environment into her own hands.
    Though many blamed the planet's escalating, unexplained climate phenomena on the advent of new technologies, the rapidly growing omnic population, and drastically increased consumption of resources, the true cause remained unknown. To find a solution, Overwatch established a series of eco-Watchpoints at remote, critical locations worldwide.
    Mei-Ling Zhou was a member of this multiyear initiative. A peerless climatologist, she had introduced cutting-edge innovations in the field of climate manipulation that protected at-risk areas in Asia and beyond. She was assigned to the program's monitoring station at Watchpoint: Antarctica when disaster struck: a sudden, catastrophic polar storm battered the installation and cut it off from the outside world, leaving the facility damaged and the scientists stranded. As their supplies dwindled, they entered cryostasis in a last-ditch effort to survive until a rescue attempt could be made.
    But that rescue never came. It was years later when the team's cryogenics chamber was finally discovered. Mei, still in hibernation, was the only survivor. The world Mei awoke to had gone through considerable changes: Overwatch was no more, the serious climate issues had worsened, and none of the eco-Watchpoints were in operation. Any clues that they had uncovered were lost.
    Mei has decided to continue her work on her own. Equipped with a portable version of her climate-manipulation technology, she travels around the world, hoping to re-establish the eco-network and track down the causes of the threats to the planet's ecosystem.",
    hero_image_one: "/images/heroImages/mei/Mei-page-one.png",
    hero_image_two: "/images/heroImages/mei/Mei-page-two.png",
    hero_gameplay_video: "Placeholder",
    hero_gameplay_description: "Mei’s weather-altering devices slow opponents and protect locations. Her Endothermic Blaster unleashes damaging icicles and frost streams, and she can Cryo-Freeze herself to guard against counterattacks, or obstruct the opposing team's movements with an Ice Wall.",
    hp: 250,
    armor: 0,
    shields: 0,
    total_hp: 250,
    playstyle: "Crowd Control",
    hero_difficulty: 3,
    weapon_one_image: "/images/heroImages/mei/Mei-gun.png",
    weapon_one_name: "Endothermic Blaster",
    weapon_one_description: "Short-range spray weapon that freezes.",
    weapon_one_type: "Beam/Crowdcontrol",
    weapon_two_image: "/images/heroImages/mei/Mei-gun.png",
    weapon_two_name: "Icicle",
    weapon_two_description: "Long-range icicle launcher.",
    weapon_two_type: "Projectile",
    passive_image: "N/A",
    passive_name: "N/A",
    passive_description: "N/A",
    ability_one_image: "/images/heroImages/mei/Mei-heal.png",
    ability_one_name: "Cryo-Freeze",
    ability_one_description: "Become invulnerable and heal yourself.",
    ability_two_image: "/images/heroImages/mei/Mei-wall.png",
    ability_two_name: "Ice Wall",
    ability_two_description: "Create a wall in front of you.",
    ability_three_image: "N/A",
    ability_three_name: "N/A",
    ability_three_description: "N/A",
    ultimate_image: "/images/heroImages/mei/Mei-blizzard.png",
    ultimate_name: "Blizzard",
    ultimate_description: "Launch a weather control drone that freezes enemies in a wide area.",
    healing_type: "N/A",
    barrier: false,
    barrier_health: 0)
Character.create(
    name: "Junkrat", 
    role: "Damage", 
    hero_card: '/images/icons/Icon-Junkrat.png', 
    role_card: '/images/icons/Icon-Damage.png',
    name_two: "Jamison Fawkes",
    age: 25,
    occupation: "	Anarchist, Thief, Demolitionist, Mercenary, Scavenger",
    base_of_operation: "Junkertown, Australia",
    affiliation: "Junkers (formerly)",
    hero_story: "Junkrat is an explosives-obsessed freak who lives to cause chaos and destruction.
    The attack on the Australian omnium's fusion core forever altered the landscape of the Outback. After the detonation, the area was transformed into a harsh, irradiated wasteland, littered with debris and the twisted fragments of the ruined facility, and unlivable to most.
    But there were some who survived. Calling themselves the Junkers, they scavenged the husk of the omnium and formed a lawless, cutthroat society in its shadow. Junkrat was one of them, eking out a living reclaiming metal and components from the ruins. Like many others, he was affected by the lingering radiation. This touch of madness made him ideal for handling dangerous explosives, a love which he turned into an obsession.
    He came to notoriety when he discovered an extremely valuable secret in the bones of the omnium. Though few knew the nature of what he found, he was nonetheless pursued by bounty hunters, gangs, and opportunists wherever he went, until he made a deal with the Junker enforcer Roadhog, who grudgingly agreed to be his personal bodyguard in exchange for a fifty-fifty share of the spoils.
    Now, with Roadhog in tow, Junkrat has left the Outback, and embarked upon an international crime spree leaving nothing but havoc and bedlam in his wake.",
    hero_image_one: "/images/heroImages/junkrat/Junkrat-page-one.png",
    hero_image_two: "/images/heroImages/junkrat/Junkrat-page-two.png",
    hero_gameplay_video: "Placeholder",
    hero_gameplay_description: "Mei’s weather-altering devices slow opponents and protect locations. Her Endothermic Blaster unleashes damaging icicles and frost streams, and she can Cryo-Freeze herself to guard against counterattacks, or obstruct the opposing team's movements with an Ice Wall.",
    hp: 200,
    armor: 0,
    shields: 0,
    total_hp: 200,
    playstyle: "Crowd Control/Spam",
    hero_difficulty: 2,
    weapon_one_image: "/images/heroImages/junkrat/Junkrat-gun.png",
    weapon_one_name: "Frag Launcher",
    weapon_one_description: "Bouncing explosive projectile weapon.",
    weapon_one_type: "Projectile/Explosive",
    weapon_two_image: "N/A",
    weapon_two_name: "N/A",
    weapon_two_description: "N/A",
    weapon_two_type: "N/A",
    passive_image: "/images/heroImages/junkrat/Junkrat-passive.png",
    passive_name: "Total Mayhem",
    passive_description: "Deals no damage to self with explosives. Drop bombs on death.",
    ability_one_image: "/images/heroImages/junkrat/Junkrat-mine.png",
    ability_one_name: "Concussion Mine",
    ability_one_description: "Throw a knockback mine with LSHIFT then detonate it with ABILITY 1.",
    ability_two_image: "/images/heroImages/junkrat/Junkrat-trap.png",
    ability_two_name: "Steel Trap",
    ability_two_description: "Place an immobilizing trap.",
    ability_three_image: "N/A",
    ability_three_name: "N/A",
    ability_three_description: "N/A",
    ultimate_image: "/images/heroImages/junkrat/Junkrat-tire.png",
    ultimate_name: "Rip-Tire",
    ultimate_description: "Drive and detonate an exploding tire.",
    healing_type: "N/A",
    barrier: false,
    barrier_health: 0)
Character.create(name: "Hanzo", role: "Damage", hero_card: '/images/icons/Icon-Hanzo.png', role_card: '/images/icons/Icon-Damage.png')
Character.create(
    name: "Genji", 
    role: "Damage", 
    hero_card: '/images/icons/Icon-Genji.png', 
    role_card: '/images/icons/Icon-Damage.png',
    name_two: "Genji Shimada",
    age: 35,
    occupation: "Adventurer",
    base_of_operation: "Shambali Monastery, Nepal",
    affiliation: "Shimada Clan (formerly), Overwatch (formerly), Blackwatch(formerly)",
    hero_story: "The cyborg Genji Shimada has made peace with the augmented body he once rejected, and in doing so, he has discovered a higher humanity.  As the youngest son of the master of the Shimada ninja clan, Genji lived a life of luxury and privilege. He had little interest in the family's illegal businesses, and although he excelled at and enjoyed his ninja training, he spent most of his time pursuing a playboy lifestyle.                       Many within the clan considered the carefree Genji to be a dangerous liability, and they resented his father for coddling and protecting him. Following the clan leader's untimely death, Genji's older brother, Hanzo, demanded that Genji take a more active role in their late father's empire. Genji refused, enraging Hanzo.                          The tension between the brothers built to a violent confrontation that left Genji on the verge of dying. Hanzo believed that he had killed his brother, but Genji was rescued by Overwatch and the intervention of Dr. Angela Ziegler. The global security force saw Genji as a potential asset in its ongoing operations to combat the Shimada clan.                         As Genji's injuries left him clinging to life, Overwatch offered to rebuild his body in exchange for his help. He was put through an extensive process of cyberization, which enhanced his natural speed and agility and augmented his superlative ninja skills. Transformed into a living weapon, Genji single-mindedly set about the task of dismantling his family's criminal empire. But as time passed, Genji felt increasingly at war with himself. He was repulsed by the mechanical parts of his body and could not come to grips with what he had become. When his mission was complete, he abandoned Overwatch and wandered the world in search of meaning. He drifted for many years before crossing paths with the omnic monk Zenyatta. Though Genji initially rejected Zenyatta's wisdom, the benevolent omnic would not be deterred. In time, Zenyatta became his mentor, and under the monk's tutelage, Genji reconciled his dual existence as both man and machine. He learned to accept that although he had a cyborg body, his human soul was intact, and he came to see his new form as a gift and a unique strength. Now, for the first time in his life, Genji is free. Even he cannot say where his path will ultimately lead.",
    hero_image_one: "/images/heroImages/genji/Genji-page-image-one.png",
    hero_image_two: "/images/heroImages/genji/Genji-page-image-two.png",
    hero_gameplay_video: "Placeholder",
    hero_gameplay_description: "Genji flings precise and deadly Shuriken at his targets, and uses his technologically-advanced katana to deflect projectiles or deliver a Swift Strike that cuts down enemies.",
    hp: 200,
    armor: 0,
    shields: 0,
    total_hp: 200,
    playstyle: "Flanker/Dive",
    hero_difficulty: 3,
    weapon_one_image: "/images/heroImages/genji/Genji-shuriken.png",
    weapon_one_name: "Shuriken",
    weapon_one_description: "Throw an accurate burst of three projectiles",
    weapon_one_type: "Projectile",
    weapon_two_image: "/images/heroImages/genji/Genji-shuriken.png",
    weapon_two_name: "Fan of Blades",
    weapon_two_description: "Throw a fan of 3 projectiles in an arc.",
    weapon_two_type: "Projectile",
    passive_image: "/images/heroImages/genji/Genji-passive.png",
    passive_name: "Cyber-Agility",
    passive_description: "Climbs walls and double jump.",
    ability_one_image: "/images/heroImages/genji/Genji-deflect.png",
    ability_one_name: "Deflect",
    ability_one_description: "Deflect incoming projectiles towards the direction you are aiming and block melee attacks.",
    ability_two_image: "/images/heroImages/genji/Genji-dash.png",
    ability_two_name: "Swift Strike",
    ability_two_description: "Rapidly dash forward and inflict damage on enemies. Eliminations reset the cooldown.",
    ability_three_image: "N/A",
    ability_three_name: "N/A",
    ability_three_description: "N/A",
    ultimate_image: "/images/heroImages/genji/Genji-dragon-blade.png",
    ultimate_name: "Dragonblade",
    ultimate_description: "Unsheathe a deadly melee weapon.",
    healing_type: "N/A",
    barrier: false,
    barrier_health: 0  
)
Character.create(name: "Echo", role: "Damage", hero_card: '/images/icons/Icon-Echo.png', role_card: '/images/icons/Icon-Damage.png')
Character.create(name: "Doomfist", role: "Damage", hero_card: '/images/icons/Icon-Doomfist.png', role_card: '/images/icons/Icon-Damage.png')
Character.create(name: "Cassidy", role: "Damage", hero_card: '/images/icons/Icon-Cassidy.png', role_card: '/images/icons/Icon-Damage.png')
Character.create(name: "Bastion", role: "Damage", hero_card: '/images/icons/Icon-Bastion.png', role_card: '/images/icons/Icon-Damage.png')
Character.create(name: "Ashe", role: "Damage", hero_card: '/images/icons/Icon-Ashe.png', role_card: '/images/icons/Icon-Damage.png')

###Tanks###
puts "Creating Tanks..."
puts 
Character.create(name: "D.Va", role: "Tank", hero_card: '/images/icons/Icon-D.Va.png', role_card: '/images/icons/Icon-Tank.png')
Character.create(name: "Orisa", role: "Tank", hero_card: '/images/icons/Icon-Orisa.png', role_card: '/images/icons/Icon-Tank.png')
Character.create(name: "Sigma", role: "Tank", hero_card: '/images/icons/Icon-Sigma.png', role_card: '/images/icons/Icon-Tank.png')
Character.create(name: "Roadhog", role: "Tank", hero_card: '/images/icons/Icon-Roadhog.png', role_card: '/images/icons/Icon-Tank.png')
Character.create(name: "Reinhardt", role: "Tank", hero_card: '/images/icons/Icon-Reinhardt.png', role_card: '/images/icons/Icon-Tank.png')
Character.create(name: "Winston", role: "Tank", hero_card: '/images/icons/Icon-Winston.png', role_card: '/images/icons/Icon-Tank.png')
Character.create(name: "Zarya", role: "Tank", hero_card: '/images/icons/Icon-Zarya.png', role_card: '/images/icons/Icon-Tank.png')
Character.create(name: "Wrecking Ball", role: "Tank", hero_card: '/images/icons/Icon-Wrecking_Ball.png', role_card: '/images/icons/Icon-Tank.png')


###Supports###
puts "Creating Supports..."
puts 
Character.create(name: "Baptiste", role: "Support", hero_card: '/images/icons/Icon-Baptiste.png', role_card: '/images/icons/Icon-Support.png')
Character.create(name: "Ana", role: "Support", hero_card: '/images/icons/Icon-Ana.png', role_card: '/images/icons/Icon-Support.png')
Character.create(name: "Mercy", role: "Support", hero_card: '/images/icons/Icon-Mercy.png', role_card: '/images/icons/Icon-Support.png')
Character.create(name: "Zenyatta", role: "Support", hero_card: '/images/icons/Icon-Zenyatta.png', role_card: '/images/icons/Icon-Support.png')
Character.create(name: "Brigitte", role: "Support", hero_card: '/images/icons/Icon-Brigitte.png', role_card: '/images/icons/Icon-Support.png')
Character.create(name: "Moira", role: "Support", hero_card: '/images/icons/Icon-Moira.png', role_card: '/images/icons/Icon-Support.png')
Character.create(name: "Lucio", role: "Support", hero_card: '/images/icons/Icon-Lucio.png', role_card: '/images/icons/Icon-Support.png')


puts "Seeding Complete!"
